### ISSUE TITLE
Get A4 output?

### ISSUE THREAD

**Issue by gsidhu** [tuxu/ethz-thesis#1]
Since this template is adapted to A5 document size, is it possible to override those settings to get the default A4 output? I tried disabling the `a5paper` option when loading classicthesis but it doesn't seem to work.

Thanks!

**Comment by tuxu** [comment]
In [thesis.tex](https://github.com/tuxu/ethz-thesis/blob/master/thesis.tex#L6), change the paper size to A4 (`paper=a4`). This should get the page size right. You also probably want to disable the `a5paper` option for ClassicThesis and change the font size. Change the size of the text body in [preamble/general.tex](https://github.com/tuxu/ethz-thesis/blob/master/preamble/general.tex#L143-L149), or remove these lines for the ClassicThesis defaults. Hope this helps!

**Comment by gsidhu** [comment]
Thank you. Appreciate the help!

I have added some comments in my local `general.tex` copy. The comments and an A4 version of your template might be useful for other newbie users/ETH students. I'll fork the repo and push a new branch when I finish my thesis. :)
