### ISSUE TITLE
Scribus error when opening cover.sla

### ISSUE THREAD

**Issue by chrislat** [tuxu/ethz-thesis#2]
Hello and thank you for sharing this template! 

When I try to open cover.sla with Scribus 1.4.6 I get an error about the file not being in an acceptable format. This is reproducible in two linux environments (OpenSUSE Leap 42.3 and Ubuntu 18.04.1).

**Comment by tuxu** [comment]
The file was created with the [development branch](https://www.scribus.net/downloads/unstable-branch/) of Scribus (1.5.x). I never actually experienced any trouble with this version. Just give it a try! The cover assistant `scribus-create-cover.py` might be compatible with 1.4, though.

**Comment by chrislat** [comment]
Thanks for the prompt response. 

Indeed everything works as expected using Scribus 1.5.x. It might be worth adding this info to cover/README.md.
