### ISSUE TITLE
Scribus fail to adjust spine width + manual fix

### ISSUE THREAD

**Issue by Bender250** [tuxu/ethz-thesis#8]
Hi, thanks for the template! I can imagine you do not have time addressing comments, so I just share my problem and the solution I used - such that others can find it, maybe it helps. It is an ugly hack, so maybe someone finds better way, but my colleagues did something similar.

**Problem:** When I open the template in Scribus (v. 1.5.8) and execute the Python script in it, the result is a blank sheet - with absolutely no content. It might be because of some version incompatibility, but in another [issue](https://github.com/tuxu/ethz-thesis/issues/2), you mentioned that it was tested with v. 1.5.x - so at least minor version is the same.

**Solution:** `cover.sla` is an XML file, you can edit the content directly, and let only Scribus render it to PDF. Some preliminaries that took me a while to figure out:
* Scribus units are "pixels", with PPI (pixel's per inch) set to 72
* A5 is 420 x 595 pixels. In the template, you can find `PAGEHEIGHT="595.275590551181"`, maybe it is to make it slightly larger or just a rounding error, but I used that number for better precision.
* The original template is computed for 100 pages.

I used the `binding.py` to compute the spine width for my thesis (162 pages), and then I checked every `*WIDTH`, `XPOS`, `VerticalGuides`, and `path` with `L8*` and changed them by the offset I got by my extra 62 pages - either the full offset for objects on the second page, or by half if the object is in the spine - you can just read the XML structure to guess it. Anyway, trial and error works well, you can always save the file, load it with Scribus, and it will render it. Besides, I already edited the texts in the template.

Finally, some cuts were still outside of the page. I fixed that in Inkscape (where you can also simply adjust some other problems), the trick was just to "Resize page to content".

I am attaching my [cover](https://github.com/tuxu/ethz-thesis/files/14536005/cover.zip) (in zip because GitHub does not allow `.sla` files). Maybe it is not perfect, but it was accepted by ETH Print&publish.

**Comment by tuxu** [comment]
Hi @Bender250, thanks for documenting your solution here. I was curious and just tried the script with Scribus 1.6.1 on macOS, but couldn't reproduce the issue. The page and the guides are created as they should. Note that the script does indeed only create a blank page with guides. Maybe guides were hidden?

**Comment by Bender250** [comment]
Hi @tuxu, thanks for the response! The script creates the spine guides, if that is all that was expected, then I am sorry, I had wrong expectations.
![Screenshot](https://github.com/tuxu/ethz-thesis/assets/3519476/826096eb-5916-49d9-aa6b-656e004531d5)

**Comment by tuxu** [comment]
I'm glad we could clarify the issue 🙂 Things are as they are because that's all I needed back then to get the correct dimensions into Scribus. With the guidelines visible it's easy to add a background and the few text boxes for author, title, etc. The included `.sla` file is just an example outcome of this workflow.
